### ISSUE TITLE
Update not showing in Extension Manager

### ISSUE THREAD

**Issue by RedBearAK** [neuromorph/custom-osd#1]
Just an FYI, I usually get notifications from Extension Manager when there are updates to extensions available, and then of course I have to log out and back in to get the updates installed (literally the worst problem with using GNOME). Haven't seen anything yet for the new update (post version 8?). 

When I open the Extension Manager app, it also seems to do a triggered refresh of available versions. It's not showing an update available for Custom OSD yet. 

Will update when it appears.

**Comment by neuromorph** [comment]
It was a heads up for upcoming update but it is yet to arrive in the extensions store. It needs to be reviewed and approved by Gnome reviewer (voluntary) and then it will become active. 
Don't worry, you will get the notification just as you expect. Hopefully soon!
