### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by zefkerr** [neuromorph/custom-osd#10]
Please

**Comment by neuromorph** [comment]
You are fast :)
I haven't looked into Gnome 46 port guide yet but it is on the cards, hopefully soon.
I will update here.

**Comment by neuromorph** [comment]
Update: 
I didn't get a chance to delve into it so it is taking longer than I thought. I plan to add some small updates/fixes while porting to 46 and will need to do tests for both 45 and 46.
Meanwhile, I just did a sanity check by updating the 'metadata.json' file to reflect Gnome 46 and it seems to work fine. So I suggest to you and anyone who stumbles here to please update the 'metadata.json' and start using the extension on Gnome 46 until the official port is released.
Thank you.

**Comment by neuromorph** [comment]
New version of Custom OSD is now live with support for Gnome 46!

UPDATE (v25, v26):
- Profiles: New default profiles added for new users to get started
- Vertical Position: Please note vertical position convention is changed: +50 is Top and -50 is Bottom of screen
- Size also changed a bit so you may need to resize existing OSDs in settings
- Square/Circle toggle option allows to get squarish/circlish shapes (as you vary Shape Shift)
- New Special Effects: Progress Ring and Background Image (see below)
- Gradient: New radial gradient direction and option to set end color opacity
- Level: New level color, opacity and thickness options
- Border: New border color, opacity and thickness options
- Padding: New horizontal and vertical padding options
- Shadow: New shadow color option
- Font: Improved implementation of font attributes (font style, stretch, weight)
- Trigger custom OSDs from command line (e.g. from a script) (see [ReadMe](https://github.com/neuromorph/custom-osd?tab=readme-ov-file#trigger-custom-osds-from-command-line) )

Progress Ring / Disk:
- Select Special Effect 'Progress Ring' in settings
- Set 'Ring Gap from Border' and 'Level Thickness' to get a Progress Ring or Progress Disk
- For Disk, set Gap to 100 and adjust Level. For Ring reduce Gap say 40-50 and adjust Level.
- Set Square / Circle On to get that shape.
- Combine with Shape Shift and color / opacity styles for fg, bg, level and border

Background Image:
- Set any image as OSD background (smaller size preferred)
- Select Special Effect 'Background Image'
- In 'Background Image File', provide path to a local file e.g. Pictures/myOsdImage.png

**Comment by zefkerr** [comment]
@neuromorph thank you!
