### ISSUE TITLE
Ubuntu 24.04 No settings

### ISSUE THREAD

**Issue by bkbilly** [neuromorph/custom-osd#12]
I've installed the latest version of Ubuntu and there is an issue showing the settings page.

![image](https://github.com/neuromorph/custom-osd/assets/518494/75e8fd18-2fff-4614-b4f3-073f7a428d0c)

Here are the Technical Details:
```
Error: Requiring Json, version none: Typelib file for namespace 'Json' (any version) not found

Stack trace:
  require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
  @gi://Json/:3:25
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by l3ifk** [comment]
I get the same error. Is there any known fix for this?

**Comment by l3ifk** [comment]
I found a solution! Seems like a package was missing, like in the error message mentioned. 
Just do `sudo apt install gir1.2-json-1.0` and logout and in again and then the settings will work again.

**Comment by bkbilly** [comment]
Thanks, this fix works for me too!
