### ISSUE TITLE
Unlock Crash

### ISSUE THREAD

**Issue by in4matix** [neuromorph/custom-osd#14]
Thank you for this awesome extension.
After unlocking PC, extension crashes:

![Screenshot from 2024-05-09 16-05-25](https://github.com/neuromorph/custom-osd/assets/62904593/b0885858-590c-4f91-b7bd-03d8d82dd7f6)

A reboot fixes it.
I am on Ubuntu 22 LTS (Gnome 42.9)

**Comment by neuromorph** [comment]
Whoa! Haven't faced it. Can you please run following command in terminal to capture the trace in journal. Then lock and unlock to trigger the crash and check the terminal for error/messages trace. It will help to find where exactly value goes out of range.

`SHELL_DEBUG=all journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

Let me know.
Thanks,

**Comment by in4matix** [comment]
Yeah, I only started using locking today, so I have also not faced it before.
Please see attached.
[cosd_log.zip](https://github.com/neuromorph/custom-osd/files/15264958/cosd_log.zip)

**Comment by neuromorph** [comment]
I always lock (have auto-locking set) but no such issue. Also it does not make sense from the log as well. It basically says that an uint returned by a javascript builtin function is not a uint :)
On the other hand it points to a line in disable which is optional so can be commented out as mentioned below. Basically, when you lock screen, Gnome disables extensions and when you unlock, Gnome enables them again (unless they ran into an error).

Go to Custom OSD, `extension.js` line 646 and comment it:-

Change ` clearTimeout(this.redrawFlagTimeoutId);` to `//  clearTimeout(this.redrawFlagTimeoutId);`

Then reload Gnome (log out and back in). Hope that fixes it.

**Comment by in4matix** [comment]
Indeed, this fixes it. Thank you!
