### ISSUE TITLE
[BUG] Coordinate fencing/default coordinates on fresh system

### ISSUE THREAD

**Issue by RedBearAK** [neuromorph/custom-osd#4]
@neuromorph 

I just installed the extension last night on a new installation of openSUSE Tumbleweed, with GNOME 44.x. 

The OSD ended up being somewhere off screen until I changed the vertical setting, then it appeared on screen. 

Changing the horizontal setting did NOT bring it onto the screen, so I think it was entirely off the screen vertically to begin with. And that seems to indicate that only the value that gets changed gets "fenced" into the screen dimensions. 

If I had to guess, the "fencing" logic that keeps the values on screen doesn't kick in until changing the value that is causing the OSD to appear off screen. 

Both values, if I recall correctly, started at 50.0, which with your coordinate offset system would imply the OSD would show up along the bottom edge right edge (bottom-right corner). 

I don't know whether this could have had an effect, but the machine is an iMac12,2 model (27-inch, 2011) with a screen that is natively 2560x1440, but I'm running it in 1920x1080 because it's sitting too far away at the moment. 

There had been no other OSD-related extension installed prior to this. The system had finished installing just about an hour earlier. So no reason for any pre-existing values other than the system defaults to have any effect on the placement. 

Prior to installing the extension, the OSD would appear in the usual place expected in GNOME 44.x. (Centered horizontally and close to the bottom edge.)

**Comment by RedBearAK** [comment]
@neuromorph 

Looks like your repo is not set up to automatically assign you to new issues. I can't recall exactly how that is done on GitHub. Maybe in the issue templates.

**Comment by neuromorph** [comment]
Yes, I found this bug a few days ago. It is also mentioned in the extension description in the Gnome extensions page as a note to new users. The issues is because of carrying forward of old defaults into the new positioning system. My bad, I forgot to update the defaults in the config in the earlier update. 
It is already fixed and will soon reflect in the next update. For now, if you set the position once, the OSD will be drawn in and stay in. Thanks for reporting. The default after update will be 0,0 so OSD will appear at center of screen for fresh install.

**Comment by neuromorph** [comment]
> @neuromorph
> 
> Looks like your repo is not set up to automatically assign you to new issues. I can't recall exactly how that is done on GitHub. Maybe in the issue templates.

Ah, I will check.

**Comment by RedBearAK** [comment]
> It is already fixed and will soon reflect in the next update.

Wondered about that. Then you will be able to close this as resolved soon. Although I guess I would need to try the extension in a new user account to be able to verify that the pure defaults work OK, after the update. 

Not too difficult. Will try to update this and close it myself when I get the update and can verify the fix on my end.

**Comment by neuromorph** [comment]
New update is live with the defaults fix. You can try it out and let me know if any issues.
Thanks for verifying!

**Comment by RedBearAK** [comment]
If it's the v12 update, I already tried it out last night, but I was a little preoccupied when I was first messing with it. Fairly sure that the foreground color after the update changed to something transparent, which led me to look into the color selector, but I found that the only way to change the opacity was to get into the custom color dialog. Was that the intention? I can't recall whether there was a custom option before, I never looked for it and didn't think about it. Maybe it was there the whole time? 

When I go into the custom color dialog and try to change settings, it doesn't retain the color, so I have to use the color dropper to grab the existing color displayed on the main window, and then adjust it from there. Kind of awkward, but I think this might be a limitation of how the color dialog and custom color dialogs work. 

I was able to create a pretty ghostly looking OSD by using some transparency on the custom color for the foreground. Kind of neat. 

I did try to reset the settings this time, and the defaults are interesting. It's centered, with a transparent light gray background color, no shadow, and a light blue main color. Trying to show off what it can do with the defaults? Pretty good choices. 

What occurred to me with all these different settings to mess with is that the extension would be significantly enhanced with the ability to save a list of named presets that the user could swap between while they get familiar with everything, or presets that go with different themes the user likes to shift between. But that could be quite a bit of work. You'd have to find a way to save all the settings somewhere, and be able to load them on demand, and display the list, etc. I don't know if there's a framework for that in the code you're dealing with, that might make it easier. Or if you want to get into it at all. 

When I did things like that in my own code I had GPT-4 helping me put it together. 

If you were going to go down that road, you could also have a list of your own built-in presets that show off what the extension can do, as well as letting the user save their own. 

Just another one of my crazy thoughts.

**Comment by RedBearAK** [comment]
I thought I was in the discussion thread, so what I previously posted here was much longer. I deleted and moved it to the other thread. 

OK, in a new user account the pure defaults are the same as I saw when I reset the extension settings in the other account. Definitely on the screen, right in the center. 

I will note that while the default color/transparency are interesting, they can make the OSD kind of difficult to see if the background happens to be bright and colorful. Which the "Welcome" window in this new openSUSE Tumbleweed user account definitely is. I had an idea where the OSD would appear and still couldn't see it for a second, until I activated some keys that would being it up a few times. 

Maybe go with a slightly darker background for a little bit more contrast. Black with 20-25% opacity? Needs to stand out whether the user has a dark theme or light theme engaged. 

If you go with a darker foreground and a white background, you'll need something more like 65-70% opacity to have it stand out on a bright, colorful background, while still letting some of the background through.

**Comment by neuromorph** [comment]
> OK, in a new user account the pure defaults are the same as I saw when I reset the extension settings in the other account. Definitely on the screen, right in the center.

Cool, :+1: 

>I will note that while the default color/transparency are interesting, they can make the OSD kind of difficult to see if the background happens to be bright and colorful.

Ah, the opacity is a bit too low. Looks good on darker backgrounds but I see it can be less so on lighter ones. Raised it, should be better in next update (will check color shade as well).

**Comment by neuromorph** [comment]
This was fixed in the following update but missed to close here. Closing now.
